### ISSUE TITLE
Is this compatible with Python 3?

### ISSUE THREAD

**Issue by jg8481it** [mseclab/PyJFuzz#4]
Just curious.

**Comment by dzonerzy** [comment]
Hello,

Right now it's not compatible , anyway it's just a matter of some print functions and just few import change , it could be done easily

Regards,
Daniele

**Comment by dzonerzy** [comment]
Hi @jg8481it ,
I Added support for python 2.6 and python 3, feel free to test, it's still a beta version but should works.

Regards,
Daniele

**Comment by jg8481it** [comment]
Thank you. I will give this a try.
