### ISSUE TITLE
Fix `long` on mutator

### ISSUE THREAD

**Issue by victorhaffreinguen26** [mseclab/PyJFuzz#7]
Hey 👋 

The `long` type is [not defined in python3](http://python3porting.com/differences.html#long). 

Can you please fix [this line](https://github.com/mseclab/PyJFuzz/blob/be2f6b068025edbb4a01771c41b7aff2e6562312/pyjfuzz/core/pjf_mutators.py#L99), either by removing it or by adding a `long = int` in your condition on the top of the file.

Thanks!

(also, you should push your new version to pypi, it's better than to install by commit 👍)

**Comment by muse-enthusiast** [comment]
Any updates on this one? 

I am running jython 2.7.1. and whenever my JSON contains any long values, I do receive the error: "[ERROR]: <type 'long'>."

**Comment by victorhaffreinguen26** [comment]
For what it's worth, you can do the following, and it fixes the issue for python3:

    RUN sed -i '/long: self.int_mutator,/d' /path/to/pyjfuzz/core/pjf_mutators.py

**Comment by dzonerzy** [comment]
fixed with  04501fc
