### ISSUE TITLE
fuzz broken

### ISSUE THREAD

**Issue by JazJas** [mseclab/PyJFuzz#9]
It looks like a recent change, commit ec5d82d24dcf341a8420a6bc6ee043f825b6fde5, fixed fuzzing -p with list, breaks the tool.

Please check Line 158 if len(self.config.parameters) < 0: in pjf_factory.py.

The sample python script like simple_fuzzer.py no longer works as expected.

**Comment by dzonerzy** [comment]
Fixed with 685e642
